import {
  Geist,
  Geist_Mono,
  Bricolage_Grotesque,
  Roboto,
} from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const bricolageGRotesque = Bricolage_Grotesque({
  variable: "--font-bricolage-grotesque",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${bricolageGRotesque.variable} ${roboto.variable} antialiased bg-base-100`}
      >
        <main className="max-w-md mx-auto bg-base-200 lg:rounded-lg min-h-screen">
          {children}
        </main>
      </body>
    </html>
  );
}
